# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription'
          scope: resourcegroup
          # Override the Subscription Id set by Azure Login.
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          # Provide the name of a resource group, only required for resource Group deployments.
          resourceGroupName: HeatherPharmaWebApp
          # Specify the path or URL to the Azure Resource Manager template.
          template: ./infra/template.json
          # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group) or Validate (only validates the template).
          deploymentMode: Complete
          # Specifies the name of the resource group deployment to create.
          deploymentName: HeatherPharmaWebDemo
          # Supply deployment parameter values.
          parameters: ./infra/parameters.json
          # Specify whether to fail the action if some data is written to stderr stream of az cli. Valid values are: true, false
          failOnStdErr: fail
