name: dotnet-build-test-publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./src
        
    env:
      AZURE_WEBAPP_NAME: HeatherPharmaWebApp          # set this to your application's name
      AZURE_WEBAPP_PACKAGE_PATH: './myapp'                  # set this to the path to your web app project, defaults to the repository root
      DOTNET_VERSION: '3.1.x'                         # set this to the dot net version to use

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK 3.1.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x
      
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      
      - name: Publish
        run: dotnet publish -c Release -o ${{ github.workspace }}
        
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          package: ${{ github.workspace }}
