name: dotnet-build-test-publish

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    
    defaults:
      run:
        working-directory: ./src
        
    env:
      AZURE_WEBAPP_NAME: dev-heather-pharma-webapp
      AZURE_WEBAPP_PACKAGE_PATH: './myapp'                 
      DOTNET_VERSION: '3.1.x'                              

    steps:
      - name: Check Out GitHub Code
        uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK 3.1.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x
      
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      
      - name: Publish
        run: dotnet publish -c Release -o ${{ github.workspace }}
        
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run Azure webapp deploy action using service principal'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          package: ${{ github.workspace }}
